### ISSUE TITLE
get security audit done by IT [Hao will lead, not implement]

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#17]

**Comment by dcarsey** [comment]
Dawn submitted a ticket to help@renci.org

**Comment by dcarsey** [comment]
I have an email in to Marcin to ask his advice WRT how to secure the site to the best of RENCI's ability.  Waiting for response.  
I also asked if there's anyone on his team with a background in security.

Also also.... my notes from our meeting indicate that we will do a full security audit later.  

I have some notes from September about a CS student who might help us with this.  The notes say "Kimberly has web page w/ email."  Also, that UNC's CS dept has a GROUP, and maybe we could give this to them as a project.

Want to add here that Dawn has a good working relationship with Kevin Jeffay, Dept Chair of CS, and he might be able to guide us further.

**Comment by krobasky** [comment]
Call with Alex Everett at ITS, will help us set-up Qualys scan of heal-ctmd, we have ask out to Marcin if RENCI has a Qualys account. We also need to give him a list of the libraries installed on each container and on the VM itself.

Suggested we use 'incommon' rather than Auth0 for single-signon, so we sent list of CTSAs for him to check on support.

Suggested 'openshift' in CloudApps for runniing containers (will reach out to Patrick Casey for next steps).

We will set-up call for later next week to follow-up

**Comment by dcarsey** [comment]
Need more info from UNC.

**Comment by dcarsey** [comment]
Closing this ticket as there are sufficient reminders / tickets for working with UNC Cloud Apps for security issues.
