### ISSUE TITLE
Report out LoE for finishing metrics

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#335]
LoE reported by Matt for finishing #336, #337, #95 (in that order):

•	Add ten columns to Sites table : by Friday, Dec 11
•	Add template download links to all upload forms: by Friday, Dec 11
•	Add two new columns to database : This one is the only tricky one. One of our developers, Shruti, who have been handling mapping and database updates like this is out, so--at worst--we would be awaiting her return in January to make this change. However, we did poke around in her source code, and it's possible that we'll have it figured out well enough to reconfigure the database ourselves.

**Comment by krobasky** [comment]
WARNING: You can't add the 10 metrics if you don't have those 2 columns.

**Comment by dcarsey** [comment]
Jackie’s feedback about the metrics

- Don’t get rid of anything yet (keep ALL metrics for now) 
- Rename queries per total data elements instead of queries per ecrf page (#347)
- Looks at total number of queries AND (add) total number of data elements - new field
- ADD total data elements to …. Wherever it goes? (field, tickbox?)
- Final protocol - using reg packet sent but Jackie checking w/ Theresa about that  (#349)
- REMINDER:  Add in 2 new fields -  lost to follow-up and data elements (this ticket #335)
- We need to double-check that all metrics have info / are being calculated (#344)
(eCRF - where is that coming from ?)
