### ISSUE TITLE
Don't try to filter test or erroneous REDCap data

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#419]
Examples:

ampersand
accent marks

**Comment by krobasky** [comment]
I don't think the problem is with allowing special characters, but rather with trying to filter out bad data. Hopefully, turning off the filter for bad/test data will solve the issue. However, in order to test that the problem is solved, we want to add precise steps to the ticket for reproducing the error. For example, what specific string was used that made the error noticeable, or what proposal was filtered, etc.

**Comment by xu-hao** [comment]
emoved the test data filter from the pipeline
