### ISSUE TITLE
Fix Build Dockerfile issue in  tic-pipeline-script

### ISSUE THREAD

**Issue by luthfib** [RENCI/ctmd#424]
Currently the build fails in because it of the Heal-data-mapping is a private repo. Close this ticket when:

- [x] We want to remove the submodule dependency from the tic map pipeline script
- [x] Add it as a dependency to the ctmd-dashboard as a submodule
- [x] Add a volume binding in the docker compose and docker compose prod to the the pipeline for mapping.json
- [x] Create a an additional ticket to explore how we can remove the dependency to mapping.json throughout the repo. Currently we have specific fields referenced throughout the repo and it would be nice if it was configuration oriented.

**Comment by krobasky** [comment]
Can we make the entire system independent of the http://github.com/RENCI/HEAL-data-mapping repo? That way we can easily demonstrate on "example" data, and publish this software for use with other initiatives, like the HEAL initiative?

For example:
1. create an "example" mapping file and add it into ctmd-dashboard so that any columns hard-coded in the dashboard can be met by the "example" mapping file (the "example" file must be designed so that it contains no TIN-business-sensitive data).
2. add the "example" filename to ctmd-dashboard/env.sample, and when configuring the REAL system, copy env.sample to .env and then replace the "example" filename with the REAL mapping file (e.g., from the private HEAL-data-mapping repo)
3. make sure the docker-compose.prod.yml maps the correct mapping file ("example" or HEAL-data-mapping) to the volume that will be used by the pipeline repo. 

In effect, we're using a mounted volume as a "shared memory" space between the dashboard and pipeline containers.

With this approach, we may want to add the private HEAL-data-mapping repo as a submodule to the ctmd repo, which doesn't have any autobuild tests so there shouldn't be any critical permission failures... I think? And if somebody tries to clone the ctmd repo, if they don't have permission to HEAL, they just won't get it.

**Comment by krobasky** [comment]
New ticket: #432

**Comment by krobasky** [comment]
https://github.com/RENCI/tic-map-pipeline-script/commit/271fefe893a6267bcb2f3cb642c4fbc5475c5190
