### ISSUE TITLE
debug stage/dev auth-t issues

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#483]
Up until ... when? a week ago? ... we were able to login to dev and stage servers by 1) logging into TIN, 2) typing in the name of the dev-, stage- server. However, now we can only login to the prod server, and we get errors from our own auth-t server when we try to login to dev or stage.

At this point, we think the error is most likely caused by some kind of change made to the authentication server at Vanderbilt, Hong recommends logging into tx-auth VM's docker container and watching the log for errors.

*Workaround*: 
1. login to TIN
2. click on 'network at work'
3. right-click on 'proposal assignments' and choose 'inspect'
4. click to open the <div> called 'new-graph-div'
5. double click the 'onclick' property of the 'img-src' element, then click it one more time to edit it, 
6. replace 'ctmd' with 'dev-ctmd' (or 'stage-ctmd') and hit ENTER
7. wait for an image (or broken image) to appear under 'proposal assignments' and click that

I'm not 100% clear on why this works; I just knowyou can't paste the 'onclick' url into the address bar, you have to execute the element. Big thanks to Matt for the tip!

Close this ticket when:
- [ ] A user can login to TIN then browse to stage-ctmd and the home page will eventually come up instead of the "Access Denide" page.

**Comment by dcarsey** [comment]
We have a problem on our CTMD site and our digging has led us to suspect that we have a mismatch in our certificates.
 Can you please check the following VMs to see that they all match and if not please advise / update the ones that need to be updated?
Auth-fuse.renci.org
Dev-auth-fuse.renci.org
Stage-auth-fuse.renci.org
Ctmd.renci.org
Stage-ctmd.renci.org
Dev-ctmd.renci.org
Heal-ctmd.renci.org
From:  Kevin Otte, RENCI ACIS
Answer #1 from Kevin
I checked all the sites listed and found that auth-fuse and dev-auth-fuse seem to be misconfigured. They are presenting a correct server certificate, but not the intermediate certificate. These appear to be handled by docker-proxy, so I'm not sure how to correct this.
Since you are using the Digicert certificate, their instructions might provide a pointer in the right direction:
https://www.digicert.com/kb/ssl-certificate-installation.htm
You may also wish to consider migrating to a Let's Encrypt certificate at this point. 
 
Answer #2 from Kevin
Further investigation finds the certificates live in /opt/certs on the host and are mapped into the container for use. I believe I can update the certificate bundle there and do a "docker restart tx-autht_txautht-nginx_1" to have it pick up.
I noticed the certificate on dev-auth-fuse was copied over from dotdsi.renci.org. While this is functional, it would be a problem if the certificate ever needed to be reissued. ACIS would not have any record of this usage of the certificate. I'll plan to issue a new certificate to cover all of the CTMD machines to help with this.
I'm 99% sure this will all work, but there's that small chance the Docker container won't restart correctly, in which case I would be uncertain of the next steps. I can do dev-auth-fuse now, and if it works move on to auth-fuse, or we can wait until after the break when folk are back.
-- 
From Hong:
I think you can run down.sh in /var/opt/auth/txautht if containers are not down already, then run up.sh in the same directory to bring all containers back up. Yes, once the certs are updated, running down.sh followed by up.sh should have new certs take effect in the container.
The path suggested by ACIS left open the possibility that after they installed the fix, the container may not come up on its own.
We’ve opted to wait until the first week in January and THEN we will give the green light to Kevin Otte to move ahead with the plan they suggested (see below).

**Comment by dcarsey** [comment]
We now have to use this workaround for logging into the HEAL site.

**Comment by dcarsey** [comment]
#510
